### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bilbolodz**
Fixed Docker RPI file
Fixed Adapter IP issue

### CODE REVIEW

**Comment by moroen** [comment]
I might be blind here, but I fail to see how this should work?

The address field is used to point to the IKEA-gateway, not to the machine where the adapter is running. How do you specify the IP of the IKEA-gateway?

**Comment by bilbolodz** [comment]
I don't quite get it. "Fixed Adapter IP issue" it's only change from hardcoded 127.0.0.1 to: "Parameters["Address"]"

**Comment by moroen** [comment]
Yes, but for the current master version, Parameters["Address"] should contain the IP of the IKEA gateway... 

So if you use it to specify the address of the adapter, you have no way of tellling the adapter the IP of the gateway, you're assuming that the IP of the adapter and the gateway is the same, which it's  definitely not...

This whole issue stems from the way I changed the handling of ip, ident/psk between master and development... The adapter in the current master needs to get the gateway IP, ident and psk from the plugin, in development ip, ident/psk is handled BY the adapter, specified in config.json..

If you need to have the adapter running on another machine than domoticz, you need to hardcode the ip of the adapter in the connectAdapter-function...

Anyway, I'm currenty working on updating the plugin for stable domoticz, so this whole issue soon be moot...

**Comment by bilbolodz** [comment]
An error in code, sorry.

**Pull request closed without merging**
